# BOOKMARKS
[[manager.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd ~/Desktop"
desc = "Go to ~/Desktop"

[[manager.prepend_keymap]]
on   = [ "g", "D" ]
run  = "cd ~/Downloads"
desc = "Go to ~/Downloads"

[[manager.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd ~/Documents/Seminary/2025_Summer"
desc = "Go to seminary folder"

# DUCK DB
# https://github.com/wylie102/duckdb.yazi?tab=readme-ov-file
[[manager.prepend_keymap]]
on = "H"
run = "plugin duckdb -1"
desc = "Scroll one column to the left"

[[manager.prepend_keymap]]
on = "L"
run = "plugin duckdb +1"
desc = "Scroll one column to the right"

# toggle-pane
# https://github.com/yazi-rs/plugins/tree/main/toggle-pane.yazi
[[manager.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
